### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by vbastos** [mlavin/sickmuse#15]
I am getting the following error installing sickmuse on my Ubuntu 14.04. I installed it with sudo pip install sickmuse.

This is the error I get:

    checking for xmlParseFile in -lxml2... yes
    checking libxml/parser.h usability... yes
    checking libxml/parser.h presence... yes
    checking for libxml/parser.h... yes
    configure: error: Please fix the library issues listed above and try again.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cGWqHu/python-rrdtool/setup.py", line 99, in <module>
        include_dirs=[include_dir],
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-cGWqHu/python-rrdtool/setup.py", line 68, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-cGWqHu/python-rrdtool/setup.py", line 62, in run
        subprocess.check_call(executable, cwd=os.path.dirname(executable))
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '/tmp/pip-build-cGWqHu/python-rrdtool/rrdtool-1.4.7/configure' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-cGWqHu/python-rrdtool/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MmqBnD-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cGWqHu/python-rrdtool

**Comment by mlavin** [comment]
You are missing the required dependencies to build `python-rrdtool`. See https://github.com/pbanaszkiewicz/python-rrdtool#installation

>A few development (header) files are required to build python-rrdtool: for Python, libcairo2, libpango, libxml2, libglib2 and librrd. In Ubuntu run: sudo apt-get install libcairo2-dev libpango1.0-dev libglib2.0-dev libxml2-dev librrd-dev
